TypeError: this.end is not a function
    at M.error (/Users/linteng/www/127/tech/node-framework/libs/contentProviders/response.js:16:10)
    at M.init (/Users/linteng/www/127/tech/node-framework/libs/contentProviders/router.js:12:21)
    at Server.Http.createServer (/Users/linteng/www/127/tech/node-framework/libs/main.js:54:24)
    at Server.emit (events.js:182:13)
    at Server.EventEmitter.emit (domain.js:442:20)
    at parserOnIncoming (_http_server.js:651:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
Error: Cannot find module '../tools/utils'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:571:15)
    at Function.Module._load (internal/modules/cjs/loader.js:497:25)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/linteng/www/127/tech/node-framework/app.js:3:21)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
/Users/linteng/www/127/tech/node-framework/libs/contentProviders/request.js:19
      }`) catch (e) {console.log(e)}
          ^^^^^

SyntaxError: Unexpected token catch
    at new Script (vm.js:74:7)
    at createScript (vm.js:246:10)
    at Object.runInThisContext (vm.js:298:10)
    at Module._compile (internal/modules/cjs/loader.js:646:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
/Users/linteng/www/127/tech/node-framework/libs/contentProviders/request.js:50
    console.log(u.searchParams.getAll(â€™))
                                      ^

SyntaxError: Invalid or unexpected token
    at new Script (vm.js:74:7)
    at createScript (vm.js:246:10)
    at Object.runInThisContext (vm.js:298:10)
    at Module._compile (internal/modules/cjs/loader.js:646:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
/Users/linteng/www/127/tech/node-framework/libs/contentProviders/request.js:10
  }
  ^

SyntaxError: Unexpected token }
    at new Script (vm.js:74:7)
    at createScript (vm.js:246:10)
    at Object.runInThisContext (vm.js:298:10)
    at Module._compile (internal/modules/cjs/loader.js:646:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
/Users/linteng/www/127/tech/node-framework/libs/contentProviders/request.js:3
const util = require('util');
^^^^^

SyntaxError: Unexpected token const
    at new Script (vm.js:74:7)
    at createScript (vm.js:246:10)
    at Object.runInThisContext (vm.js:298:10)
    at Module._compile (internal/modules/cjs/loader.js:646:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
/Users/linteng/www/127/tech/node-framework/libs/contentProviders/request.js:3
const util = require('util');
^^^^^

SyntaxError: Unexpected token const
    at new Script (vm.js:74:7)
    at createScript (vm.js:246:10)
    at Object.runInThisContext (vm.js:298:10)
    at Module._compile (internal/modules/cjs/loader.js:646:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
ReferenceError: req is not defined
    at cb (/Users/linteng/www/127/tech/node-framework/libs/contentProviders/request.js:32:20)
    at IncomingMessage.req.on (/Users/linteng/www/127/tech/node-framework/libs/contentProviders/request.js:51:23)
    at IncomingMessage.emit (events.js:182:13)
    at IncomingMessage.EventEmitter.emit (domain.js:442:20)
    at endReadableNT (_stream_readable.js:1091:14)
    at process._tickCallback (internal/process/next_tick.js:174:19)
/Users/linteng/www/127/tech/node-framework/libs/contentProviders/request.js:36
          console.log({fields: fields, files: files}))
                                                     ^

SyntaxError: Unexpected token )
    at new Script (vm.js:74:7)
    at createScript (vm.js:246:10)
    at Object.runInThisContext (vm.js:298:10)
    at Module._compile (internal/modules/cjs/loader.js:646:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
ReferenceError: Utils is not defined
    at Object.<anonymous> (/Users/linteng/www/127/tech/node-framework/libs/contentProviders/request.js:4:16)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/linteng/www/127/tech/node-framework/libs/main.js:2:17)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
ReferenceError: Utils is not defined
    at Object.<anonymous> (/Users/linteng/www/127/tech/node-framework/libs/contentProviders/request.js:4:16)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/linteng/www/127/tech/node-framework/libs/main.js:2:17)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
ReferenceError: Utils is not defined
    at Object.<anonymous> (/Users/linteng/www/127/tech/node-framework/libs/contentProviders/request.js:4:16)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/linteng/www/127/tech/node-framework/libs/main.js:2:17)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
ReferenceError: Utils is not defined
    at Object.<anonymous> (/Users/linteng/www/127/tech/node-framework/libs/contentProviders/request.js:4:14)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/linteng/www/127/tech/node-framework/libs/main.js:2:17)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
ReferenceError: Utils is not defined
    at Object.<anonymous> (/Users/linteng/www/127/tech/node-framework/libs/contentProviders/request.js:4:14)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/linteng/www/127/tech/node-framework/libs/main.js:2:17)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
ReferenceError: Utils is not defined
    at Object.<anonymous> (/Users/linteng/www/127/tech/node-framework/libs/contentProviders/request.js:5:16)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/linteng/www/127/tech/node-framework/libs/main.js:2:17)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
ReferenceError: Utils is not defined
    at Object.<anonymous> (/Users/linteng/www/127/tech/node-framework/libs/contentProviders/request.js:5:16)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/linteng/www/127/tech/node-framework/libs/main.js:2:17)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
ReferenceError: Utils is not defined
    at Object.<anonymous> (/Users/linteng/www/127/tech/node-framework/libs/contentProviders/request.js:5:16)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/linteng/www/127/tech/node-framework/libs/main.js:2:17)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
ReferenceError: Utils is not defined
    at Object.<anonymous> (/Users/linteng/www/127/tech/node-framework/libs/contentProviders/request.js:5:16)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/linteng/www/127/tech/node-framework/libs/main.js:2:17)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
ReferenceError: Utils is not defined
    at Object.<anonymous> (/Users/linteng/www/127/tech/node-framework/libs/contentProviders/request.js:5:16)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/linteng/www/127/tech/node-framework/libs/main.js:2:17)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
ReferenceError: Utils is not defined
    at Object.<anonymous> (/Users/linteng/www/127/tech/node-framework/libs/contentProviders/request.js:5:16)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/linteng/www/127/tech/node-framework/libs/main.js:2:17)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
ReferenceError: Utils is not defined
    at Object.<anonymous> (/Users/linteng/www/127/tech/node-framework/libs/contentProviders/request.js:5:16)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/linteng/www/127/tech/node-framework/libs/main.js:2:17)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
ReferenceError: Utils is not defined
    at Object.<anonymous> (/Users/linteng/www/127/tech/node-framework/libs/contentProviders/request.js:5:16)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/linteng/www/127/tech/node-framework/libs/main.js:2:17)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
ReferenceError: Utils is not defined
    at Object.<anonymous> (/Users/linteng/www/127/tech/node-framework/libs/contentProviders/request.js:5:16)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/linteng/www/127/tech/node-framework/libs/main.js:2:17)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
ReferenceError: Utils is not defined
    at Object.<anonymous> (/Users/linteng/www/127/tech/node-framework/libs/contentProviders/request.js:5:16)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/linteng/www/127/tech/node-framework/libs/main.js:2:17)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
ReferenceError: Utils is not defined
    at Object.<anonymous> (/Users/linteng/www/127/tech/node-framework/libs/contentProviders/request.js:5:16)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/linteng/www/127/tech/node-framework/libs/main.js:2:17)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
ReferenceError: Utils is not defined
    at Object.<anonymous> (/Users/linteng/www/127/tech/node-framework/libs/contentProviders/request.js:4:13)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/linteng/www/127/tech/node-framework/libs/main.js:2:17)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
ReferenceError: Utils is not defined
    at Object.<anonymous> (/Users/linteng/www/127/tech/node-framework/libs/contentProviders/request.js:4:13)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/linteng/www/127/tech/node-framework/libs/main.js:2:17)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
TypeError: part.on is not a function
    at IncomingForm.handlePart (/Users/linteng/www/127/tech/node-framework/node_modules/formidable/lib/incoming_form.js:191:10)
    at IncomingForm.onPart (/Users/linteng/www/127/tech/node-framework/node_modules/formidable/lib/incoming_form.js:179:8)
    at cb (/Users/linteng/www/127/tech/node-framework/libs/contentProviders/request.js:67:14)
    at IncomingMessage.req.on (/Users/linteng/www/127/tech/node-framework/libs/contentProviders/request.js:105:15)
    at IncomingMessage.emit (events.js:182:13)
    at IncomingMessage.EventEmitter.emit (domain.js:442:20)
    at endReadableNT (_stream_readable.js:1091:14)
    at process._tickCallback (internal/process/next_tick.js:174:19)
Error: Request aborted
    at IncomingMessage.<anonymous> (/Users/linteng/www/127/tech/node-framework/node_modules/formidable/lib/incoming_form.js:122:19)
    at IncomingMessage.emit (events.js:182:13)
    at IncomingMessage.EventEmitter.emit (domain.js:442:20)
    at abortIncoming (_http_server.js:443:9)
    at socketOnClose (_http_server.js:437:3)
    at Socket.emit (events.js:187:15)
    at Socket.EventEmitter.emit (domain.js:442:20)
    at TCP._handle.close [as _onclose] (net.js:598:12)
/Users/linteng/www/127/tech/node-framework/libs/main.js:58
        await this.Queue.shift()
        ^^^^^

SyntaxError: await is only valid in async function
    at new Script (vm.js:74:7)
    at createScript (vm.js:246:10)
    at Object.runInThisContext (vm.js:298:10)
    at Module._compile (internal/modules/cjs/loader.js:646:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
/Users/linteng/www/127/tech/node-framework/libs/main.js:58
        await this.Queue.shift()
        ^^^^^

SyntaxError: await is only valid in async function
    at new Script (vm.js:74:7)
    at createScript (vm.js:246:10)
    at Object.runInThisContext (vm.js:298:10)
    at Module._compile (internal/modules/cjs/loader.js:646:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
TypeError: Cannot read property 'push' of undefined
    at M.use (/Users/linteng/www/127/tech/node-framework/libs/main.js:66:16)
    at Object.<anonymous> (/Users/linteng/www/127/tech/node-framework/app.js:13:5)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at /usr/local/lib/node_modules/pm2/lib/ProcessContainer.js:331:23
    at /usr/local/lib/node_modules/pm2/node_modules/async/dist/async.js:473:16
    at next (/usr/local/lib/node_modules/pm2/node_modules/async/dist/async.js:5315:29)
TypeError: Cannot read property 'push' of undefined
    at M.use (/Users/linteng/www/127/tech/node-framework/libs/main.js:66:16)
    at Object.<anonymous> (/Users/linteng/www/127/tech/node-framework/app.js:13:5)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at /usr/local/lib/node_modules/pm2/lib/ProcessContainer.js:331:23
    at /usr/local/lib/node_modules/pm2/node_modules/async/dist/async.js:473:16
    at next (/usr/local/lib/node_modules/pm2/node_modules/async/dist/async.js:5315:29)
/Users/linteng/www/127/tech/node-framework/libs/main.js:63
        console.log(Utils
                    ^^^^^

SyntaxError: missing ) after argument list
    at new Script (vm.js:74:7)
    at createScript (vm.js:246:10)
    at Object.runInThisContext (vm.js:298:10)
    at Module._compile (internal/modules/cjs/loader.js:646:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
ReferenceError: Utils is not defined
    at Object.<anonymous> (/Users/linteng/www/127/tech/node-framework/libs/contentProviders/request.js:5:16)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/linteng/www/127/tech/node-framework/libs/main.js:3:17)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
ReferenceError: Utils is not defined
    at Object.<anonymous> (/Users/linteng/www/127/tech/node-framework/libs/contentProviders/request.js:5:16)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/linteng/www/127/tech/node-framework/libs/main.js:3:17)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
ReferenceError: Utils is not defined
    at Object.<anonymous> (/Users/linteng/www/127/tech/node-framework/libs/contentProviders/request.js:5:16)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/linteng/www/127/tech/node-framework/libs/main.js:3:17)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
ReferenceError: Utils is not defined
    at Object.<anonymous> (/Users/linteng/www/127/tech/node-framework/libs/contentProviders/request.js:5:16)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/linteng/www/127/tech/node-framework/libs/main.js:3:17)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
ReferenceError: Utils is not defined
    at Object.<anonymous> (/Users/linteng/www/127/tech/node-framework/libs/contentProviders/request.js:5:16)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/linteng/www/127/tech/node-framework/libs/main.js:3:17)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
ReferenceError: Utils is not defined
    at Object.<anonymous> (/Users/linteng/www/127/tech/node-framework/libs/contentProviders/request.js:5:16)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/linteng/www/127/tech/node-framework/libs/main.js:3:17)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
Error: Cannot find module './contentProviders/router'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:571:15)
    at Function.Module._load (internal/modules/cjs/loader.js:497:25)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/linteng/www/127/tech/node-framework/libs/main.js:5:16)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
Error: Cannot find module './contentProviders/request'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:571:15)
    at Function.Module._load (internal/modules/cjs/loader.js:497:25)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/linteng/www/127/tech/node-framework/libs/main.js:3:17)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
Error: Cannot find module './contentProviders/request'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:571:15)
    at Function.Module._load (internal/modules/cjs/loader.js:497:25)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/linteng/www/127/tech/node-framework/libs/main.js:3:17)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
Error: Cannot find module './contentProviders/request'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:571:15)
    at Function.Module._load (internal/modules/cjs/loader.js:497:25)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/linteng/www/127/tech/node-framework/libs/main.js:3:17)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
Error: Cannot find module './contentProviders/request'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:571:15)
    at Function.Module._load (internal/modules/cjs/loader.js:497:25)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/linteng/www/127/tech/node-framework/libs/main.js:3:17)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
Error: Cannot find module './contentProviders/request'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:571:15)
    at Function.Module._load (internal/modules/cjs/loader.js:497:25)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/linteng/www/127/tech/node-framework/libs/main.js:3:17)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
Error: Cannot find module './contentProviders/request'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:571:15)
    at Function.Module._load (internal/modules/cjs/loader.js:497:25)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/linteng/www/127/tech/node-framework/libs/main.js:3:17)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
Error: Cannot find module './contentProviders/request'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:571:15)
    at Function.Module._load (internal/modules/cjs/loader.js:497:25)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/linteng/www/127/tech/node-framework/libs/main.js:3:17)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
Error: Cannot find module './contentProviders/request'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:571:15)
    at Function.Module._load (internal/modules/cjs/loader.js:497:25)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/linteng/www/127/tech/node-framework/libs/main.js:3:17)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
Error: Cannot find module './render/controller'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:571:15)
    at Function.Module._load (internal/modules/cjs/loader.js:497:25)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at M._init (/Users/linteng/www/127/tech/node-framework/libs/main.js:17:25)
    at new M (/Users/linteng/www/127/tech/node-framework/libs/main.js:12:10)
    at Object.<anonymous> (/Users/linteng/www/127/tech/node-framework/app.js:2:13)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
Error: Cannot find module './render/controller'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:571:15)
    at Function.Module._load (internal/modules/cjs/loader.js:497:25)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at M._init (/Users/linteng/www/127/tech/node-framework/libs/main.js:17:25)
    at new M (/Users/linteng/www/127/tech/node-framework/libs/main.js:12:10)
    at Object.<anonymous> (/Users/linteng/www/127/tech/node-framework/app.js:2:13)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
/Users/linteng/www/127/tech/node-framework/libs/session/redis.js:11
    try () {
        ^

SyntaxError: Unexpected token (
    at new Script (vm.js:74:7)
    at createScript (vm.js:246:10)
    at Object.runInThisContext (vm.js:298:10)
    at Module._compile (internal/modules/cjs/loader.js:646:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
Error: Cannot find module './config/allow_origin_white'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:571:15)
    at Function.Module._load (internal/modules/cjs/loader.js:497:25)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/linteng/www/127/tech/node-framework/app.js:4:13)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
Error: Cannot find module './config/redis'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:571:15)
    at Function.Module._load (internal/modules/cjs/loader.js:497:25)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/linteng/www/127/tech/node-framework/libs/main.js:8:21)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
Error: Cannot find module './config/redis'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:571:15)
    at Function.Module._load (internal/modules/cjs/loader.js:497:25)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/linteng/www/127/tech/node-framework/libs/main.js:8:21)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
Error: Cannot find module './config/redis'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:571:15)
    at Function.Module._load (internal/modules/cjs/loader.js:497:25)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/linteng/www/127/tech/node-framework/libs/main.js:8:21)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
Error: Cannot find module './config/redis'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:571:15)
    at Function.Module._load (internal/modules/cjs/loader.js:497:25)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/linteng/www/127/tech/node-framework/libs/main.js:8:21)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
Error: Cannot find module './config/redis'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:571:15)
    at Function.Module._load (internal/modules/cjs/loader.js:497:25)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/linteng/www/127/tech/node-framework/libs/main.js:8:21)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
Error: Cannot find module './config/redis'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:571:15)
    at Function.Module._load (internal/modules/cjs/loader.js:497:25)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/linteng/www/127/tech/node-framework/libs/main.js:8:21)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
Error: Cannot find module './libs/main'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:571:15)
    at Function.Module._load (internal/modules/cjs/loader.js:497:25)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/linteng/www/127/tech/node-framework/app.js:1:76)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
Error: Cannot find module './config/redis'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:571:15)
    at Function.Module._load (internal/modules/cjs/loader.js:497:25)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/linteng/www/127/tech/node-framework/core/main.js:8:21)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
Error: Cannot find module './config/redis'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:571:15)
    at Function.Module._load (internal/modules/cjs/loader.js:497:25)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/linteng/www/127/tech/node-framework/core/main.js:8:21)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
Error: Cannot find module '../config/redis'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:571:15)
    at Function.Module._load (internal/modules/cjs/loader.js:497:25)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/linteng/www/127/tech/node-framework/core/main.js:8:21)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
Error: Cannot find module '../config/redis'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:571:15)
    at Function.Module._load (internal/modules/cjs/loader.js:497:25)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/linteng/www/127/tech/node-framework/core/main.js:8:21)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
/Users/linteng/www/127/tech/node-framework/core/session/redis.js:9
        this[v].on('error', err => process.exit(1);)
                                                 ^

SyntaxError: missing ) after argument list
    at new Script (vm.js:74:7)
    at createScript (vm.js:246:10)
    at Object.runInThisContext (vm.js:298:10)
    at Module._compile (internal/modules/cjs/loader.js:646:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
ReferenceError: redisConfig is not defined
    at Object.<anonymous> (/Users/linteng/www/127/tech/node-framework/core/main.js:8:1)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/linteng/www/127/tech/node-framework/app.js:1:76)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
TypeError: Cannot assign to read only property 'prototype' of function 'class M {
  constructor() {
    console.log(this)
  }
}'
    at M._init (/Users/linteng/www/127/tech/node-framework/core/main.js:21:26)
    at new M (/Users/linteng/www/127/tech/node-framework/core/main.js:15:10)
    at Object.<anonymous> (/Users/linteng/www/127/tech/node-framework/app.js:2:13)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at /usr/local/lib/node_modules/pm2/lib/ProcessContainer.js:331:23
    at /usr/local/lib/node_modules/pm2/node_modules/async/dist/async.js:473:16
TypeError: Cannot assign to read only property 'prototype' of function 'class M {
  constructor() {
    console.log(this)
  }
}'
    at M._init (/Users/linteng/www/127/tech/node-framework/core/main.js:21:26)
    at new M (/Users/linteng/www/127/tech/node-framework/core/main.js:15:10)
    at Object.<anonymous> (/Users/linteng/www/127/tech/node-framework/app.js:2:13)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at /usr/local/lib/node_modules/pm2/lib/ProcessContainer.js:331:23
    at /usr/local/lib/node_modules/pm2/node_modules/async/dist/async.js:473:16
TypeError: Cannot assign to read only property 'prototype' of function 'class M {
  constructor() {
    console.log(this)
  }
}'
    at M._init (/Users/linteng/www/127/tech/node-framework/core/main.js:22:26)
    at new M (/Users/linteng/www/127/tech/node-framework/core/main.js:15:10)
    at Object.<anonymous> (/Users/linteng/www/127/tech/node-framework/app.js:2:13)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at /usr/local/lib/node_modules/pm2/lib/ProcessContainer.js:331:23
    at /usr/local/lib/node_modules/pm2/node_modules/async/dist/async.js:473:16
ReferenceError: Super is not defined
    at M._init (/Users/linteng/www/127/tech/node-framework/core/main.js:22:32)
    at new M (/Users/linteng/www/127/tech/node-framework/core/main.js:15:10)
    at Object.<anonymous> (/Users/linteng/www/127/tech/node-framework/app.js:2:13)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at /usr/local/lib/node_modules/pm2/lib/ProcessContainer.js:331:23
    at /usr/local/lib/node_modules/pm2/node_modules/async/dist/async.js:473:16
RangeError: Maximum call stack size exceeded
    at assertPath (path.js:37:20)
    at Object.isAbsolute (path.js:1146:5)
    at Function.Module._findPath (internal/modules/cjs/loader.js:213:12)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:568:25)
    at Function.Module._load (internal/modules/cjs/loader.js:497:25)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at M._init (/Users/linteng/www/127/tech/node-framework/core/main.js:20:25)
    at new M (/Users/linteng/www/127/tech/node-framework/core/main.js:15:10)
    at M._init (/Users/linteng/www/127/tech/node-framework/core/main.js:22:28)
RangeError: Maximum call stack size exceeded
    at normalizeString (path.js:57:25)
    at Object.resolve (path.js:1105:20)
    at Function.Module._resolveLookupPaths (internal/modules/cjs/loader.js:457:17)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:564:20)
    at Function.Module._load (internal/modules/cjs/loader.js:497:25)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at M._init (/Users/linteng/www/127/tech/node-framework/core/main.js:20:25)
    at new M (/Users/linteng/www/127/tech/node-framework/core/main.js:15:10)
    at M._init (/Users/linteng/www/127/tech/node-framework/core/main.js:21:28)
RangeError: Maximum call stack size exceeded
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:537:35)
    at Function.Module._load (internal/modules/cjs/loader.js:497:25)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at M._init (/Users/linteng/www/127/tech/node-framework/core/main.js:20:25)
    at new M (/Users/linteng/www/127/tech/node-framework/core/main.js:15:10)
    at M._init (/Users/linteng/www/127/tech/node-framework/core/main.js:21:28)
    at new M (/Users/linteng/www/127/tech/node-framework/core/main.js:15:10)
    at M._init (/Users/linteng/www/127/tech/node-framework/core/main.js:21:28)
    at new M (/Users/linteng/www/127/tech/node-framework/core/main.js:15:10)
/Users/linteng/www/127/tech/node-framework/core/session/redis.js:14
    this.uuid = Sec.md5(this.ctx.request.headers('user-agent')) + '_' + 
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

ReferenceError: Invalid left-hand side in assignment
    at new Script (vm.js:74:7)
    at createScript (vm.js:246:10)
    at Object.runInThisContext (vm.js:298:10)
    at Module._compile (internal/modules/cjs/loader.js:646:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
/Users/linteng/www/127/tech/node-framework/core/session/redis.js:14
    this.uuid = Sec.md5(this.ctx.request.headers('user-agent')) + '_' + 
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

ReferenceError: Invalid left-hand side in assignment
    at new Script (vm.js:74:7)
    at createScript (vm.js:246:10)
    at Object.runInThisContext (vm.js:298:10)
    at Module._compile (internal/modules/cjs/loader.js:646:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
ReferenceError: Utils is not defined
    at Object.<anonymous> (/Users/linteng/www/127/tech/node-framework/app.js:3:21)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at /usr/local/lib/node_modules/pm2/lib/ProcessContainer.js:331:23
    at /usr/local/lib/node_modules/pm2/node_modules/async/dist/async.js:473:16
    at next (/usr/local/lib/node_modules/pm2/node_modules/async/dist/async.js:5315:29)
    at /usr/local/lib/node_modules/pm2/node_modules/async/dist/async.js:958:16
ReferenceError: Utils is not defined
    at Object.<anonymous> (/Users/linteng/www/127/tech/node-framework/app.js:3:21)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at /usr/local/lib/node_modules/pm2/lib/ProcessContainer.js:331:23
    at /usr/local/lib/node_modules/pm2/node_modules/async/dist/async.js:473:16
    at next (/usr/local/lib/node_modules/pm2/node_modules/async/dist/async.js:5315:29)
    at /usr/local/lib/node_modules/pm2/node_modules/async/dist/async.js:958:16
ReferenceError: Utils is not defined
    at Object.<anonymous> (/Users/linteng/www/127/tech/node-framework/app.js:3:21)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at /usr/local/lib/node_modules/pm2/lib/ProcessContainer.js:331:23
    at /usr/local/lib/node_modules/pm2/node_modules/async/dist/async.js:473:16
    at next (/usr/local/lib/node_modules/pm2/node_modules/async/dist/async.js:5315:29)
    at /usr/local/lib/node_modules/pm2/node_modules/async/dist/async.js:958:16
Error: Cannot find module './core/main'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:571:15)
    at Function.Module._load (internal/modules/cjs/loader.js:497:25)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/linteng/www/127/tech/node-framework/app.js:1:76)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
TypeError: Cannot assign to read only property 'bind' of object '#<Object>'
    at M._init (/Users/linteng/www/127/tech/node-framework/libs/main.js:24:16)
    at new M (/Users/linteng/www/127/tech/node-framework/libs/main.js:17:10)
    at Object.<anonymous> (/Users/linteng/www/127/tech/node-framework/app.js:2:13)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at /usr/local/lib/node_modules/pm2/lib/ProcessContainer.js:331:23
    at /usr/local/lib/node_modules/pm2/node_modules/async/dist/async.js:473:16
TypeError: Cannot assign to read only property 'bind' of object '#<Object>'
    at M._init (/Users/linteng/www/127/tech/node-framework/libs/main.js:24:16)
    at new M (/Users/linteng/www/127/tech/node-framework/libs/main.js:17:10)
    at Object.<anonymous> (/Users/linteng/www/127/tech/node-framework/app.js:2:13)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at /usr/local/lib/node_modules/pm2/lib/ProcessContainer.js:331:23
    at /usr/local/lib/node_modules/pm2/node_modules/async/dist/async.js:473:16
TypeError: Cannot assign to read only property 'bind' of object '#<Object>'
    at M._init (/Users/linteng/www/127/tech/node-framework/libs/main.js:24:16)
    at new M (/Users/linteng/www/127/tech/node-framework/libs/main.js:17:10)
    at Object.<anonymous> (/Users/linteng/www/127/tech/node-framework/app.js:2:13)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at /usr/local/lib/node_modules/pm2/lib/ProcessContainer.js:331:23
    at /usr/local/lib/node_modules/pm2/node_modules/async/dist/async.js:473:16
TypeError: Cannot assign to read only property 'bind' of object '#<Object>'
    at M._init (/Users/linteng/www/127/tech/node-framework/libs/main.js:24:16)
    at new M (/Users/linteng/www/127/tech/node-framework/libs/main.js:17:10)
    at Object.<anonymous> (/Users/linteng/www/127/tech/node-framework/app.js:2:13)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at /usr/local/lib/node_modules/pm2/lib/ProcessContainer.js:331:23
    at /usr/local/lib/node_modules/pm2/node_modules/async/dist/async.js:473:16
TypeError: resolve is not a function
    at Object.<anonymous> (/Users/linteng/www/127/tech/node-framework/app.js:8:9)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at /usr/local/lib/node_modules/pm2/lib/ProcessContainer.js:331:23
    at /usr/local/lib/node_modules/pm2/node_modules/async/dist/async.js:473:16
    at next (/usr/local/lib/node_modules/pm2/node_modules/async/dist/async.js:5315:29)
    at /usr/local/lib/node_modules/pm2/node_modules/async/dist/async.js:958:16
TypeError: Cannot destructure property `resolve` of 'undefined' or 'null'.
    at Object.<anonymous> (/Users/linteng/www/127/tech/node-framework/app.js:3:21)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at /usr/local/lib/node_modules/pm2/lib/ProcessContainer.js:331:23
    at /usr/local/lib/node_modules/pm2/node_modules/async/dist/async.js:473:16
    at next (/usr/local/lib/node_modules/pm2/node_modules/async/dist/async.js:5315:29)
    at /usr/local/lib/node_modules/pm2/node_modules/async/dist/async.js:958:16
TypeError: Cannot destructure property `resolve` of 'undefined' or 'null'.
    at Object.<anonymous> (/Users/linteng/www/127/tech/node-framework/app.js:3:21)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at /usr/local/lib/node_modules/pm2/lib/ProcessContainer.js:331:23
    at /usr/local/lib/node_modules/pm2/node_modules/async/dist/async.js:473:16
    at next (/usr/local/lib/node_modules/pm2/node_modules/async/dist/async.js:5315:29)
    at /usr/local/lib/node_modules/pm2/node_modules/async/dist/async.js:958:16
/Users/linteng/www/127/tech/node-framework/libs/tools/bind.js:2
  console.log([....new Set(arguments)])
                  ^

SyntaxError: Unexpected token .
    at new Script (vm.js:74:7)
    at createScript (vm.js:246:10)
    at Object.runInThisContext (vm.js:298:10)
    at Module._compile (internal/modules/cjs/loader.js:646:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
ReferenceError: Utils is not defined
    at Object.<anonymous> (/Users/linteng/www/127/tech/node-framework/libs/main.js:87:1)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/linteng/www/127/tech/node-framework/app.js:1:76)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
TypeError: this[i].bind is not a function
    at new M (/Users/linteng/www/127/tech/node-framework/libs/main.js:19:25)
    at Object.<anonymous> (/Users/linteng/www/127/tech/node-framework/app.js:2:13)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at /usr/local/lib/node_modules/pm2/lib/ProcessContainer.js:331:23
    at /usr/local/lib/node_modules/pm2/node_modules/async/dist/async.js:473:16
    at next (/usr/local/lib/node_modules/pm2/node_modules/async/dist/async.js:5315:29)
/Users/linteng/www/127/tech/node-framework/libs/main.js:66
      this = Utils.bind(this)
      ^^^^

ReferenceError: Invalid left-hand side in assignment
    at new Script (vm.js:74:7)
    at createScript (vm.js:246:10)
    at Object.runInThisContext (vm.js:298:10)
    at Module._compile (internal/modules/cjs/loader.js:646:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
/Users/linteng/www/127/tech/node-framework/libs/main.js:66
      this = Utils.bind(this)
      ^^^^

ReferenceError: Invalid left-hand side in assignment
    at new Script (vm.js:74:7)
    at createScript (vm.js:246:10)
    at Object.runInThisContext (vm.js:298:10)
    at Module._compile (internal/modules/cjs/loader.js:646:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
ReferenceError: Utils is not defined
    at Object.<anonymous> (/Users/linteng/www/127/tech/node-framework/libs/configure.js:1:83)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/linteng/www/127/tech/node-framework/libs/main.js:11:16)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
ReferenceError: Utils is not defined
    at Object.<anonymous> (/Users/linteng/www/127/tech/node-framework/libs/configure.js:1:83)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/linteng/www/127/tech/node-framework/libs/main.js:11:16)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
ReferenceError: Utils is not defined
    at Object.<anonymous> (/Users/linteng/www/127/tech/node-framework/libs/configure.js:1:83)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/linteng/www/127/tech/node-framework/libs/main.js:11:16)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
ReferenceError: Utils is not defined
    at Object.<anonymous> (/Users/linteng/www/127/tech/node-framework/libs/configure.js:1:83)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/linteng/www/127/tech/node-framework/libs/main.js:11:16)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
ReferenceError: Utils is not defined
    at Object.<anonymous> (/Users/linteng/www/127/tech/node-framework/libs/configure.js:1:83)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/linteng/www/127/tech/node-framework/libs/main.js:11:16)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
ReferenceError: Utils is not defined
    at Object.<anonymous> (/Users/linteng/www/127/tech/node-framework/libs/configure.js:1:83)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/linteng/www/127/tech/node-framework/libs/main.js:11:16)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
ReferenceError: Utils is not defined
    at Object.<anonymous> (/Users/linteng/www/127/tech/node-framework/libs/renderer/controller.js:1:80)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at M._init (/Users/linteng/www/127/tech/node-framework/libs/main.js:22:25)
    at new M (/Users/linteng/www/127/tech/node-framework/libs/main.js:17:10)
ReferenceError: Utils is not defined
    at Object.<anonymous> (/Users/linteng/www/127/tech/node-framework/libs/renderer/controller.js:1:80)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at new M (/Users/linteng/www/127/tech/node-framework/libs/main.js:17:25)
    at Object.<anonymous> (/Users/linteng/www/127/tech/node-framework/app.js:2:13)
ReferenceError: Utils is not defined
    at Object.<anonymous> (/Users/linteng/www/127/tech/node-framework/libs/renderer/controller.js:1:80)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at new M (/Users/linteng/www/127/tech/node-framework/libs/main.js:17:25)
    at Object.<anonymous> (/Users/linteng/www/127/tech/node-framework/app.js:2:13)
/Users/linteng/www/127/tech/node-framework/libs/renderer/template.js:20
  static _fixTpl (h) {
         ^^^^^^^

SyntaxError: Unexpected identifier
    at new Script (vm.js:74:7)
    at createScript (vm.js:246:10)
    at Object.runInThisContext (vm.js:298:10)
    at Module._compile (internal/modules/cjs/loader.js:646:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
Error: Cannot find module '../config/cache/redis'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:571:15)
    at Function.Module._load (internal/modules/cjs/loader.js:497:25)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/linteng/www/127/tech/node-framework/app.js:5:23)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
Error: Cannot find module '../config/cache/redis'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:571:15)
    at Function.Module._load (internal/modules/cjs/loader.js:497:25)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/linteng/www/127/tech/node-framework/app.js:5:23)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
Error: Cannot find module '../config/cache/redis'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:571:15)
    at Function.Module._load (internal/modules/cjs/loader.js:497:25)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/linteng/www/127/tech/node-framework/app.js:5:23)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
Error: Cannot find module '../config/cache/redis'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:571:15)
    at Function.Module._load (internal/modules/cjs/loader.js:497:25)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/linteng/www/127/tech/node-framework/libs/main.js:9:23)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
Error: Cannot find module '../config/cache/redis'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:571:15)
    at Function.Module._load (internal/modules/cjs/loader.js:497:25)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/linteng/www/127/tech/node-framework/libs/main.js:9:23)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
Error: Cannot find module '../config/cache/redis'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:571:15)
    at Function.Module._load (internal/modules/cjs/loader.js:497:25)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/linteng/www/127/tech/node-framework/libs/main.js:9:23)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
ReferenceError: sessionConfig is not defined
    at Object.<anonymous> (/Users/linteng/www/127/tech/node-framework/app.js:17:8)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at /usr/local/lib/node_modules/pm2/lib/ProcessContainer.js:331:23
    at /usr/local/lib/node_modules/pm2/node_modules/async/dist/async.js:473:16
    at next (/usr/local/lib/node_modules/pm2/node_modules/async/dist/async.js:5315:29)
    at /usr/local/lib/node_modules/pm2/node_modules/async/dist/async.js:958:16
Error: Cannot find module './config/cache/development_db'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:571:15)
    at Function.Module._load (internal/modules/cjs/loader.js:497:25)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/linteng/www/127/tech/node-framework/app.js:7:18)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
Error: Cannot find module './config/cache/development_db'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:571:15)
    at Function.Module._load (internal/modules/cjs/loader.js:497:25)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/linteng/www/127/tech/node-framework/app.js:7:18)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
/Users/linteng/www/127/tech/node-framework/libs/dbmanager/mysql.js:9
    };);
    ^

SyntaxError: missing ) after argument list
    at new Script (vm.js:74:7)
    at createScript (vm.js:246:10)
    at Object.runInThisContext (vm.js:298:10)
    at Module._compile (internal/modules/cjs/loader.js:646:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
/Users/linteng/www/127/tech/node-framework/libs/dbmanager/mysql.js:144
  }
  ^

SyntaxError: Unexpected token }
    at new Script (vm.js:74:7)
    at createScript (vm.js:246:10)
    at Object.runInThisContext (vm.js:298:10)
    at Module._compile (internal/modules/cjs/loader.js:646:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
(node:59672) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 uncaughtException listeners added. Use emitter.setMaxListeners() to increase limit
[ioredis] Unhandled error event: Error: All sentinels are unreachable. Retrying from scratch after 10ms. Last error: Connection is closed.
    at Promise (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:55:31)
    at new Promise (<anonymous>)
    at connectToNext (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:41:37)
    at resolve (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:100:29)
    at client.sentinel (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:139:24)
    at tryCatcher (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/utils.js:11:23)
    at promise.then (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/index.js:30:51)
    at process._tickCallback (internal/process/next_tick.js:178:7)
[ioredis] Unhandled error event: Error: All sentinels are unreachable. Retrying from scratch after 10ms. Last error: Connection is closed.
    at Promise (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:55:31)
    at new Promise (<anonymous>)
    at connectToNext (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:41:37)
    at resolve (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:100:29)
    at client.sentinel (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:156:24)
    at tryCatcher (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/utils.js:11:23)
    at promise.then (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/index.js:30:51)
    at process._tickCallback (internal/process/next_tick.js:178:7)
[ioredis] Unhandled error event: Error: All sentinels are unreachable. Retrying from scratch after 20ms. Last error: Connection is closed.
    at Promise (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:55:31)
    at new Promise (<anonymous>)
    at connectToNext (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:41:37)
    at resolve (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:100:29)
    at client.sentinel (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:139:24)
    at tryCatcher (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/utils.js:11:23)
    at promise.then (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/index.js:30:51)
    at process._tickCallback (internal/process/next_tick.js:178:7)
[ioredis] Unhandled error event: Error: All sentinels are unreachable. Retrying from scratch after 20ms. Last error: Connection is closed.
    at Promise (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:55:31)
    at new Promise (<anonymous>)
    at connectToNext (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:41:37)
    at resolve (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:100:29)
    at client.sentinel (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:156:24)
    at tryCatcher (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/utils.js:11:23)
    at promise.then (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/index.js:30:51)
    at process._tickCallback (internal/process/next_tick.js:178:7)
[ioredis] Unhandled error event: Error: All sentinels are unreachable. Retrying from scratch after 30ms. Last error: Connection is closed.
    at Promise (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:55:31)
    at new Promise (<anonymous>)
    at connectToNext (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:41:37)
    at resolve (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:100:29)
    at client.sentinel (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:139:24)
    at tryCatcher (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/utils.js:11:23)
    at promise.then (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/index.js:30:51)
    at process._tickCallback (internal/process/next_tick.js:178:7)
[ioredis] Unhandled error event: Error: All sentinels are unreachable. Retrying from scratch after 30ms. Last error: Connection is closed.
    at Promise (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:55:31)
    at new Promise (<anonymous>)
    at connectToNext (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:41:37)
    at resolve (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:100:29)
    at client.sentinel (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:156:24)
    at tryCatcher (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/utils.js:11:23)
    at promise.then (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/index.js:30:51)
    at process._tickCallback (internal/process/next_tick.js:178:7)
[ioredis] Unhandled error event: Error: All sentinels are unreachable. Retrying from scratch after 40ms. Last error: Connection is closed.
    at Promise (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:55:31)
    at new Promise (<anonymous>)
    at connectToNext (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:41:37)
    at resolve (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:100:29)
    at client.sentinel (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:139:24)
    at tryCatcher (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/utils.js:11:23)
    at promise.then (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/index.js:30:51)
    at process._tickCallback (internal/process/next_tick.js:178:7)
[ioredis] Unhandled error event: Error: All sentinels are unreachable. Retrying from scratch after 40ms. Last error: Connection is closed.
    at Promise (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:55:31)
    at new Promise (<anonymous>)
    at connectToNext (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:41:37)
    at resolve (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:100:29)
    at client.sentinel (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:156:24)
    at tryCatcher (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/utils.js:11:23)
    at promise.then (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/index.js:30:51)
    at process._tickCallback (internal/process/next_tick.js:178:7)
[ioredis] Unhandled error event: Error: All sentinels are unreachable. Retrying from scratch after 50ms. Last error: Connection is closed.
    at Promise (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:55:31)
    at new Promise (<anonymous>)
    at connectToNext (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:41:37)
    at resolve (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:100:29)
    at client.sentinel (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:139:24)
    at tryCatcher (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/utils.js:11:23)
    at promise.then (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/index.js:30:51)
    at process._tickCallback (internal/process/next_tick.js:178:7)
[ioredis] Unhandled error event: Error: All sentinels are unreachable. Retrying from scratch after 50ms. Last error: Connection is closed.
    at Promise (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:55:31)
    at new Promise (<anonymous>)
    at connectToNext (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:41:37)
    at resolve (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:100:29)
    at client.sentinel (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:156:24)
    at tryCatcher (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/utils.js:11:23)
    at promise.then (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/index.js:30:51)
    at process._tickCallback (internal/process/next_tick.js:178:7)
[ioredis] Unhandled error event: Error: All sentinels are unreachable. Retrying from scratch after 60ms. Last error: Connection is closed.
    at Promise (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:55:31)
    at new Promise (<anonymous>)
    at connectToNext (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:41:37)
    at resolve (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:100:29)
    at client.sentinel (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:139:24)
    at tryCatcher (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/utils.js:11:23)
    at promise.then (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/index.js:30:51)
    at process._tickCallback (internal/process/next_tick.js:178:7)
[ioredis] Unhandled error event: Error: All sentinels are unreachable. Retrying from scratch after 60ms. Last error: Connection is closed.
    at Promise (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:55:31)
    at new Promise (<anonymous>)
    at connectToNext (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:41:37)
    at resolve (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:100:29)
    at client.sentinel (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:156:24)
    at tryCatcher (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/utils.js:11:23)
    at promise.then (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/index.js:30:51)
    at process._tickCallback (internal/process/next_tick.js:178:7)
[ioredis] Unhandled error event: Error: All sentinels are unreachable. Retrying from scratch after 70ms. Last error: Connection is closed.
    at Promise (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:55:31)
    at new Promise (<anonymous>)
    at connectToNext (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:41:37)
    at resolve (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:100:29)
    at client.sentinel (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:156:24)
    at tryCatcher (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/utils.js:11:23)
    at promise.then (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/index.js:30:51)
    at process._tickCallback (internal/process/next_tick.js:178:7)
[ioredis] Unhandled error event: Error: All sentinels are unreachable. Retrying from scratch after 70ms. Last error: Connection is closed.
    at Promise (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:55:31)
    at new Promise (<anonymous>)
    at connectToNext (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:41:37)
    at resolve (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:100:29)
    at client.sentinel (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:139:24)
    at tryCatcher (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/utils.js:11:23)
    at promise.then (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/index.js:30:51)
    at process._tickCallback (internal/process/next_tick.js:178:7)
[ioredis] Unhandled error event: Error: All sentinels are unreachable. Retrying from scratch after 80ms. Last error: Connection is closed.
    at Promise (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:55:31)
    at new Promise (<anonymous>)
    at connectToNext (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:41:37)
    at resolve (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:100:29)
    at client.sentinel (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:156:24)
    at tryCatcher (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/utils.js:11:23)
    at promise.then (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/index.js:30:51)
    at process._tickCallback (internal/process/next_tick.js:178:7)
[ioredis] Unhandled error event: Error: All sentinels are unreachable. Retrying from scratch after 80ms. Last error: Connection is closed.
    at Promise (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:55:31)
    at new Promise (<anonymous>)
    at connectToNext (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:41:37)
    at resolve (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:100:29)
    at client.sentinel (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:139:24)
    at tryCatcher (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/utils.js:11:23)
    at promise.then (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/index.js:30:51)
    at process._tickCallback (internal/process/next_tick.js:178:7)
[ioredis] Unhandled error event: Error: All sentinels are unreachable. Retrying from scratch after 90ms. Last error: Connection is closed.
    at Promise (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:55:31)
    at new Promise (<anonymous>)
    at connectToNext (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:41:37)
    at resolve (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:100:29)
    at client.sentinel (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:156:24)
    at tryCatcher (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/utils.js:11:23)
    at promise.then (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/index.js:30:51)
    at process._tickCallback (internal/process/next_tick.js:178:7)
[ioredis] Unhandled error event: Error: All sentinels are unreachable. Retrying from scratch after 90ms. Last error: Connection is closed.
    at Promise (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:55:31)
    at new Promise (<anonymous>)
    at connectToNext (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:41:37)
    at resolve (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:100:29)
    at client.sentinel (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:139:24)
    at tryCatcher (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/utils.js:11:23)
    at promise.then (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/index.js:30:51)
    at process._tickCallback (internal/process/next_tick.js:178:7)
[ioredis] Unhandled error event: Error: All sentinels are unreachable. Retrying from scratch after 100ms. Last error: Connection is closed.
    at Promise (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:55:31)
    at new Promise (<anonymous>)
    at connectToNext (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:41:37)
    at resolve (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:100:29)
    at client.sentinel (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:156:24)
    at tryCatcher (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/utils.js:11:23)
    at promise.then (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/index.js:30:51)
    at process._tickCallback (internal/process/next_tick.js:178:7)
[ioredis] Unhandled error event: Error: All sentinels are unreachable. Retrying from scratch after 100ms. Last error: Connection is closed.
    at Promise (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:55:31)
    at new Promise (<anonymous>)
    at connectToNext (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:41:37)
    at resolve (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:100:29)
    at client.sentinel (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:139:24)
    at tryCatcher (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/utils.js:11:23)
    at promise.then (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/index.js:30:51)
    at process._tickCallback (internal/process/next_tick.js:178:7)
[ioredis] Unhandled error event: Error: All sentinels are unreachable. Retrying from scratch after 110ms. Last error: Connection is closed.
    at Promise (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:55:31)
    at new Promise (<anonymous>)
    at connectToNext (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:41:37)
    at resolve (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:100:29)
    at client.sentinel (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:139:24)
    at tryCatcher (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/utils.js:11:23)
    at promise.then (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/index.js:30:51)
    at process._tickCallback (internal/process/next_tick.js:178:7)
[ioredis] Unhandled error event: Error: All sentinels are unreachable. Retrying from scratch after 110ms. Last error: Connection is closed.
    at Promise (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:55:31)
    at new Promise (<anonymous>)
    at connectToNext (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:41:37)
    at resolve (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:100:29)
    at client.sentinel (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:156:24)
    at tryCatcher (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/utils.js:11:23)
    at promise.then (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/index.js:30:51)
    at process._tickCallback (internal/process/next_tick.js:178:7)
[ioredis] Unhandled error event: Error: All sentinels are unreachable. Retrying from scratch after 120ms. Last error: Connection is closed.
    at Promise (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:55:31)
    at new Promise (<anonymous>)
    at connectToNext (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:41:37)
    at resolve (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:100:29)
    at client.sentinel (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:139:24)
    at tryCatcher (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/utils.js:11:23)
    at promise.then (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/index.js:30:51)
    at process._tickCallback (internal/process/next_tick.js:178:7)
[ioredis] Unhandled error event: Error: All sentinels are unreachable. Retrying from scratch after 120ms. Last error: Connection is closed.
    at Promise (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:55:31)
    at new Promise (<anonymous>)
    at connectToNext (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:41:37)
    at resolve (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:100:29)
    at client.sentinel (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:156:24)
    at tryCatcher (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/utils.js:11:23)
    at promise.then (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/index.js:30:51)
    at process._tickCallback (internal/process/next_tick.js:178:7)
[ioredis] Unhandled error event: Error: All sentinels are unreachable. Retrying from scratch after 130ms. Last error: Connection is closed.
    at Promise (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:55:31)
    at new Promise (<anonymous>)
    at connectToNext (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:41:37)
    at resolve (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:100:29)
    at client.sentinel (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:156:24)
    at tryCatcher (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/utils.js:11:23)
    at promise.then (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/index.js:30:51)
    at process._tickCallback (internal/process/next_tick.js:178:7)
[ioredis] Unhandled error event: Error: All sentinels are unreachable. Retrying from scratch after 130ms. Last error: Connection is closed.
    at Promise (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:55:31)
    at new Promise (<anonymous>)
    at connectToNext (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:41:37)
    at resolve (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:100:29)
    at client.sentinel (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:139:24)
    at tryCatcher (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/utils.js:11:23)
    at promise.then (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/index.js:30:51)
    at process._tickCallback (internal/process/next_tick.js:178:7)
[ioredis] Unhandled error event: Error: All sentinels are unreachable. Retrying from scratch after 140ms. Last error: Connection is closed.
    at Promise (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:55:31)
    at new Promise (<anonymous>)
    at connectToNext (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:41:37)
    at resolve (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:100:29)
    at client.sentinel (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:156:24)
    at tryCatcher (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/utils.js:11:23)
    at promise.then (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/index.js:30:51)
    at process._tickCallback (internal/process/next_tick.js:178:7)
[ioredis] Unhandled error event: Error: All sentinels are unreachable. Retrying from scratch after 140ms. Last error: Connection is closed.
    at Promise (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:55:31)
    at new Promise (<anonymous>)
    at connectToNext (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:41:37)
    at resolve (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:100:29)
    at client.sentinel (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:139:24)
    at tryCatcher (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/utils.js:11:23)
    at promise.then (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/index.js:30:51)
    at process._tickCallback (internal/process/next_tick.js:178:7)
[ioredis] Unhandled error event: Error: All sentinels are unreachable. Retrying from scratch after 150ms. Last error: Connection is closed.
    at Promise (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:55:31)
    at new Promise (<anonymous>)
    at connectToNext (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:41:37)
    at resolve (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:100:29)
    at client.sentinel (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:139:24)
    at tryCatcher (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/utils.js:11:23)
    at promise.then (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/index.js:30:51)
    at process._tickCallback (internal/process/next_tick.js:178:7)
[ioredis] Unhandled error event: Error: All sentinels are unreachable. Retrying from scratch after 150ms. Last error: Connection is closed.
    at Promise (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:55:31)
    at new Promise (<anonymous>)
    at connectToNext (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:41:37)
    at resolve (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:100:29)
    at client.sentinel (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:156:24)
    at tryCatcher (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/utils.js:11:23)
    at promise.then (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/index.js:30:51)
    at process._tickCallback (internal/process/next_tick.js:178:7)
[ioredis] Unhandled error event: Error: All sentinels are unreachable. Retrying from scratch after 160ms. Last error: Connection is closed.
    at Promise (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:55:31)
    at new Promise (<anonymous>)
    at connectToNext (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:41:37)
    at resolve (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:100:29)
    at client.sentinel (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:156:24)
    at tryCatcher (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/utils.js:11:23)
    at promise.then (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/index.js:30:51)
    at process._tickCallback (internal/process/next_tick.js:178:7)
[ioredis] Unhandled error event: Error: All sentinels are unreachable. Retrying from scratch after 160ms. Last error: Connection is closed.
    at Promise (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:55:31)
    at new Promise (<anonymous>)
    at connectToNext (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:41:37)
    at resolve (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:100:29)
    at client.sentinel (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:139:24)
    at tryCatcher (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/utils.js:11:23)
    at promise.then (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/index.js:30:51)
    at process._tickCallback (internal/process/next_tick.js:178:7)
[ioredis] Unhandled error event: Error: All sentinels are unreachable. Retrying from scratch after 170ms. Last error: Connection is closed.
    at Promise (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:55:31)
    at new Promise (<anonymous>)
    at connectToNext (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:41:37)
    at resolve (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:100:29)
    at client.sentinel (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:139:24)
    at tryCatcher (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/utils.js:11:23)
    at promise.then (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/index.js:30:51)
    at process._tickCallback (internal/process/next_tick.js:178:7)
[ioredis] Unhandled error event: Error: All sentinels are unreachable. Retrying from scratch after 170ms. Last error: Connection is closed.
    at Promise (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:55:31)
    at new Promise (<anonymous>)
    at connectToNext (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:41:37)
    at resolve (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:100:29)
    at client.sentinel (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:156:24)
    at tryCatcher (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/utils.js:11:23)
    at promise.then (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/index.js:30:51)
    at process._tickCallback (internal/process/next_tick.js:178:7)
[ioredis] Unhandled error event: Error: All sentinels are unreachable. Retrying from scratch after 180ms. Last error: Connection is closed.
    at Promise (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:55:31)
    at new Promise (<anonymous>)
    at connectToNext (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:41:37)
    at resolve (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:100:29)
    at client.sentinel (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:156:24)
    at tryCatcher (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/utils.js:11:23)
    at promise.then (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/index.js:30:51)
    at process._tickCallback (internal/process/next_tick.js:178:7)
[ioredis] Unhandled error event: Error: All sentinels are unreachable. Retrying from scratch after 180ms. Last error: Connection is closed.
    at Promise (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:55:31)
    at new Promise (<anonymous>)
    at connectToNext (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:41:37)
    at resolve (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:100:29)
    at client.sentinel (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:139:24)
    at tryCatcher (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/utils.js:11:23)
    at promise.then (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/index.js:30:51)
    at process._tickCallback (internal/process/next_tick.js:178:7)
[ioredis] Unhandled error event: Error: All sentinels are unreachable. Retrying from scratch after 190ms. Last error: Connection is closed.
    at Promise (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:55:31)
    at new Promise (<anonymous>)
    at connectToNext (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:41:37)
    at resolve (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:100:29)
    at client.sentinel (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:156:24)
    at tryCatcher (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/utils.js:11:23)
    at promise.then (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/index.js:30:51)
    at process._tickCallback (internal/process/next_tick.js:178:7)
[ioredis] Unhandled error event: Error: All sentinels are unreachable. Retrying from scratch after 190ms. Last error: Connection is closed.
    at Promise (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:55:31)
    at new Promise (<anonymous>)
    at connectToNext (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:41:37)
    at resolve (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:100:29)
    at client.sentinel (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:139:24)
    at tryCatcher (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/utils.js:11:23)
    at promise.then (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/index.js:30:51)
    at process._tickCallback (internal/process/next_tick.js:178:7)
[ioredis] Unhandled error event: Error: All sentinels are unreachable. Retrying from scratch after 200ms. Last error: Connection is closed.
    at Promise (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:55:31)
    at new Promise (<anonymous>)
    at connectToNext (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:41:37)
    at resolve (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:100:29)
    at client.sentinel (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:139:24)
    at tryCatcher (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/utils.js:11:23)
    at promise.then (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/index.js:30:51)
    at process._tickCallback (internal/process/next_tick.js:178:7)
[ioredis] Unhandled error event: Error: All sentinels are unreachable. Retrying from scratch after 200ms. Last error: Connection is closed.
    at Promise (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:55:31)
    at new Promise (<anonymous>)
    at connectToNext (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:41:37)
    at resolve (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:100:29)
    at client.sentinel (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:156:24)
    at tryCatcher (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/utils.js:11:23)
    at promise.then (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/index.js:30:51)
    at process._tickCallback (internal/process/next_tick.js:178:7)
[ioredis] Unhandled error event: Error: All sentinels are unreachable. Retrying from scratch after 210ms. Last error: Connection is closed.
    at Promise (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:55:31)
    at new Promise (<anonymous>)
    at connectToNext (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:41:37)
    at resolve (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:100:29)
    at client.sentinel (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:139:24)
    at tryCatcher (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/utils.js:11:23)
    at promise.then (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/index.js:30:51)
    at process._tickCallback (internal/process/next_tick.js:178:7)
[ioredis] Unhandled error event: Error: All sentinels are unreachable. Retrying from scratch after 210ms. Last error: Connection is closed.
    at Promise (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:55:31)
    at new Promise (<anonymous>)
    at connectToNext (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:41:37)
    at resolve (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:100:29)
    at client.sentinel (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:156:24)
    at tryCatcher (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/utils.js:11:23)
    at promise.then (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/index.js:30:51)
    at process._tickCallback (internal/process/next_tick.js:178:7)
[ioredis] Unhandled error event: Error: All sentinels are unreachable. Retrying from scratch after 220ms. Last error: Connection is closed.
    at Promise (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:55:31)
    at new Promise (<anonymous>)
    at connectToNext (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:41:37)
    at resolve (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:100:29)
    at client.sentinel (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:139:24)
    at tryCatcher (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/utils.js:11:23)
    at promise.then (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/index.js:30:51)
    at process._tickCallback (internal/process/next_tick.js:178:7)
[ioredis] Unhandled error event: Error: All sentinels are unreachable. Retrying from scratch after 220ms. Last error: Connection is closed.
    at Promise (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:55:31)
    at new Promise (<anonymous>)
    at connectToNext (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:41:37)
    at resolve (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:100:29)
    at client.sentinel (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:156:24)
    at tryCatcher (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/utils.js:11:23)
    at promise.then (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/index.js:30:51)
    at process._tickCallback (internal/process/next_tick.js:178:7)
[ioredis] Unhandled error event: Error: All sentinels are unreachable. Retrying from scratch after 230ms. Last error: Connection is closed.
    at Promise (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:55:31)
    at new Promise (<anonymous>)
    at connectToNext (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:41:37)
    at resolve (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:100:29)
    at client.sentinel (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:156:24)
    at tryCatcher (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/utils.js:11:23)
    at promise.then (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/index.js:30:51)
    at process._tickCallback (internal/process/next_tick.js:178:7)
[ioredis] Unhandled error event: Error: All sentinels are unreachable. Retrying from scratch after 230ms. Last error: Connection is closed.
    at Promise (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:55:31)
    at new Promise (<anonymous>)
    at connectToNext (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:41:37)
    at resolve (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:100:29)
    at client.sentinel (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:139:24)
    at tryCatcher (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/utils.js:11:23)
    at promise.then (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/index.js:30:51)
    at process._tickCallback (internal/process/next_tick.js:178:7)
[ioredis] Unhandled error event: Error: All sentinels are unreachable. Retrying from scratch after 240ms. Last error: Connection is closed.
    at Promise (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:55:31)
    at new Promise (<anonymous>)
    at connectToNext (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:41:37)
    at resolve (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:100:29)
    at client.sentinel (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:156:24)
    at tryCatcher (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/utils.js:11:23)
    at promise.then (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/index.js:30:51)
    at process._tickCallback (internal/process/next_tick.js:178:7)
[ioredis] Unhandled error event: Error: All sentinels are unreachable. Retrying from scratch after 240ms. Last error: Connection is closed.
    at Promise (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:55:31)
    at new Promise (<anonymous>)
    at connectToNext (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:41:37)
    at resolve (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:100:29)
    at client.sentinel (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:139:24)
    at tryCatcher (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/utils.js:11:23)
    at promise.then (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/index.js:30:51)
    at process._tickCallback (internal/process/next_tick.js:178:7)
[ioredis] Unhandled error event: Error: All sentinels are unreachable. Retrying from scratch after 250ms. Last error: Connection is closed.
    at Promise (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:55:31)
    at new Promise (<anonymous>)
    at connectToNext (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:41:37)
    at resolve (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:100:29)
    at client.sentinel (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:139:24)
    at tryCatcher (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/utils.js:11:23)
    at promise.then (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/index.js:30:51)
    at process._tickCallback (internal/process/next_tick.js:178:7)
[ioredis] Unhandled error event: Error: All sentinels are unreachable. Retrying from scratch after 250ms. Last error: Connection is closed.
    at Promise (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:55:31)
    at new Promise (<anonymous>)
    at connectToNext (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:41:37)
    at resolve (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:100:29)
    at client.sentinel (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:156:24)
    at tryCatcher (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/utils.js:11:23)
    at promise.then (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/index.js:30:51)
    at process._tickCallback (internal/process/next_tick.js:178:7)
[ioredis] Unhandled error event: Error: All sentinels are unreachable. Retrying from scratch after 260ms. Last error: Connection is closed.
    at Promise (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:55:31)
    at new Promise (<anonymous>)
    at connectToNext (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:41:37)
    at resolve (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:100:29)
    at client.sentinel (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:139:24)
    at tryCatcher (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/utils.js:11:23)
    at promise.then (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/index.js:30:51)
    at process._tickCallback (internal/process/next_tick.js:178:7)
[ioredis] Unhandled error event: Error: All sentinels are unreachable. Retrying from scratch after 260ms. Last error: Connection is closed.
    at Promise (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:55:31)
    at new Promise (<anonymous>)
    at connectToNext (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:41:37)
    at resolve (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:100:29)
    at client.sentinel (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:156:24)
    at tryCatcher (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/utils.js:11:23)
    at promise.then (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/index.js:30:51)
    at process._tickCallback (internal/process/next_tick.js:178:7)
[ioredis] Unhandled error event: Error: All sentinels are unreachable. Retrying from scratch after 270ms. Last error: Connection is closed.
    at Promise (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:55:31)
    at new Promise (<anonymous>)
    at connectToNext (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:41:37)
    at resolve (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:100:29)
    at client.sentinel (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:156:24)
    at tryCatcher (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/utils.js:11:23)
    at promise.then (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/index.js:30:51)
    at process._tickCallback (internal/process/next_tick.js:178:7)
[ioredis] Unhandled error event: Error: All sentinels are unreachable. Retrying from scratch after 270ms. Last error: Connection is closed.
    at Promise (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:55:31)
    at new Promise (<anonymous>)
    at connectToNext (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:41:37)
    at resolve (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:100:29)
    at client.sentinel (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:139:24)
    at tryCatcher (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/utils.js:11:23)
    at promise.then (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/index.js:30:51)
    at process._tickCallback (internal/process/next_tick.js:178:7)
[ioredis] Unhandled error event: Error: All sentinels are unreachable. Retrying from scratch after 280ms. Last error: Connection is closed.
    at Promise (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:55:31)
    at new Promise (<anonymous>)
    at connectToNext (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:41:37)
    at resolve (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:100:29)
    at client.sentinel (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:156:24)
    at tryCatcher (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/utils.js:11:23)
    at promise.then (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/index.js:30:51)
    at process._tickCallback (internal/process/next_tick.js:178:7)
[ioredis] Unhandled error event: Error: All sentinels are unreachable. Retrying from scratch after 280ms. Last error: Connection is closed.
    at Promise (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:55:31)
    at new Promise (<anonymous>)
    at connectToNext (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:41:37)
    at resolve (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:100:29)
    at client.sentinel (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:139:24)
    at tryCatcher (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/utils.js:11:23)
    at promise.then (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/index.js:30:51)
    at process._tickCallback (internal/process/next_tick.js:178:7)
[ioredis] Unhandled error event: Error: All sentinels are unreachable. Retrying from scratch after 290ms. Last error: Connection is closed.
    at Promise (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:55:31)
    at new Promise (<anonymous>)
    at connectToNext (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:41:37)
    at resolve (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:100:29)
    at client.sentinel (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:156:24)
    at tryCatcher (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/utils.js:11:23)
    at promise.then (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/index.js:30:51)
    at process._tickCallback (internal/process/next_tick.js:178:7)
[ioredis] Unhandled error event: Error: All sentinels are unreachable. Retrying from scratch after 290ms. Last error: Connection is closed.
    at Promise (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:55:31)
    at new Promise (<anonymous>)
    at connectToNext (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:41:37)
    at resolve (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:100:29)
    at client.sentinel (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:139:24)
    at tryCatcher (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/utils.js:11:23)
    at promise.then (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/index.js:30:51)
    at process._tickCallback (internal/process/next_tick.js:178:7)
[ioredis] Unhandled error event: Error: All sentinels are unreachable. Retrying from scratch after 300ms. Last error: Connection is closed.
    at Promise (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:55:31)
    at new Promise (<anonymous>)
    at connectToNext (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:41:37)
    at resolve (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:100:29)
    at client.sentinel (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:139:24)
    at tryCatcher (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/utils.js:11:23)
    at promise.then (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/index.js:30:51)
    at process._tickCallback (internal/process/next_tick.js:178:7)
[ioredis] Unhandled error event: Error: All sentinels are unreachable. Retrying from scratch after 300ms. Last error: Connection is closed.
    at Promise (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:55:31)
    at new Promise (<anonymous>)
    at connectToNext (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:41:37)
    at resolve (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:100:29)
    at client.sentinel (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:156:24)
    at tryCatcher (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/utils.js:11:23)
    at promise.then (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/index.js:30:51)
    at process._tickCallback (internal/process/next_tick.js:178:7)
[ioredis] Unhandled error event: Error: All sentinels are unreachable. Retrying from scratch after 310ms. Last error: Connection is closed.
    at Promise (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:55:31)
    at new Promise (<anonymous>)
    at connectToNext (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:41:37)
    at resolve (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:100:29)
    at client.sentinel (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:139:24)
    at tryCatcher (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/utils.js:11:23)
    at promise.then (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/index.js:30:51)
    at process._tickCallback (internal/process/next_tick.js:178:7)
[ioredis] Unhandled error event: Error: All sentinels are unreachable. Retrying from scratch after 310ms. Last error: Connection is closed.
    at Promise (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:55:31)
    at new Promise (<anonymous>)
    at connectToNext (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:41:37)
    at resolve (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:100:29)
    at client.sentinel (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:156:24)
    at tryCatcher (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/utils.js:11:23)
    at promise.then (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/index.js:30:51)
    at process._tickCallback (internal/process/next_tick.js:178:7)
[ioredis] Unhandled error event: Error: All sentinels are unreachable. Retrying from scratch after 320ms. Last error: Connection is closed.
    at Promise (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:55:31)
    at new Promise (<anonymous>)
    at connectToNext (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:41:37)
    at resolve (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:100:29)
    at client.sentinel (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:156:24)
    at tryCatcher (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/utils.js:11:23)
    at promise.then (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/index.js:30:51)
    at process._tickCallback (internal/process/next_tick.js:178:7)
[ioredis] Unhandled error event: Error: All sentinels are unreachable. Retrying from scratch after 320ms. Last error: Connection is closed.
    at Promise (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:55:31)
    at new Promise (<anonymous>)
    at connectToNext (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:41:37)
    at resolve (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:100:29)
    at client.sentinel (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:139:24)
    at tryCatcher (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/utils.js:11:23)
    at promise.then (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/index.js:30:51)
    at process._tickCallback (internal/process/next_tick.js:178:7)
[ioredis] Unhandled error event: Error: All sentinels are unreachable. Retrying from scratch after 330ms. Last error: Connection is closed.
    at Promise (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:55:31)
    at new Promise (<anonymous>)
    at connectToNext (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:41:37)
    at resolve (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:100:29)
    at client.sentinel (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:156:24)
    at tryCatcher (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/utils.js:11:23)
    at promise.then (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/index.js:30:51)
    at process._tickCallback (internal/process/next_tick.js:178:7)
[ioredis] Unhandled error event: Error: All sentinels are unreachable. Retrying from scratch after 330ms. Last error: Connection is closed.
    at Promise (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:55:31)
    at new Promise (<anonymous>)
    at connectToNext (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:41:37)
    at resolve (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:100:29)
    at client.sentinel (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:139:24)
    at tryCatcher (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/utils.js:11:23)
    at promise.then (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/index.js:30:51)
    at process._tickCallback (internal/process/next_tick.js:178:7)
[ioredis] Unhandled error event: Error: All sentinels are unreachable. Retrying from scratch after 340ms. Last error: Connection is closed.
    at Promise (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:55:31)
    at new Promise (<anonymous>)
    at connectToNext (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:41:37)
    at resolve (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:100:29)
    at client.sentinel (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:156:24)
    at tryCatcher (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/utils.js:11:23)
    at promise.then (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/index.js:30:51)
    at process._tickCallback (internal/process/next_tick.js:178:7)
[ioredis] Unhandled error event: Error: All sentinels are unreachable. Retrying from scratch after 340ms. Last error: Connection is closed.
    at Promise (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:55:31)
    at new Promise (<anonymous>)
    at connectToNext (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:41:37)
    at resolve (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:100:29)
    at client.sentinel (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:139:24)
    at tryCatcher (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/utils.js:11:23)
    at promise.then (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/index.js:30:51)
    at process._tickCallback (internal/process/next_tick.js:178:7)
[ioredis] Unhandled error event: Error: All sentinels are unreachable. Retrying from scratch after 350ms. Last error: Connection is closed.
    at Promise (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:55:31)
    at new Promise (<anonymous>)
    at connectToNext (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:41:37)
    at resolve (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:100:29)
    at client.sentinel (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:156:24)
    at tryCatcher (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/utils.js:11:23)
    at promise.then (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/index.js:30:51)
    at process._tickCallback (internal/process/next_tick.js:178:7)
[ioredis] Unhandled error event: Error: All sentinels are unreachable. Retrying from scratch after 350ms. Last error: Connection is closed.
    at Promise (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:55:31)
    at new Promise (<anonymous>)
    at connectToNext (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:41:37)
    at resolve (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:100:29)
    at client.sentinel (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:139:24)
    at tryCatcher (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/utils.js:11:23)
    at promise.then (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/index.js:30:51)
    at process._tickCallback (internal/process/next_tick.js:178:7)
[ioredis] Unhandled error event: Error: All sentinels are unreachable. Retrying from scratch after 360ms. Last error: Connection is closed.
    at Promise (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:55:31)
    at new Promise (<anonymous>)
    at connectToNext (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:41:37)
    at resolve (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:100:29)
    at client.sentinel (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:156:24)
    at tryCatcher (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/utils.js:11:23)
    at promise.then (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/index.js:30:51)
    at process._tickCallback (internal/process/next_tick.js:178:7)
[ioredis] Unhandled error event: Error: All sentinels are unreachable. Retrying from scratch after 360ms. Last error: Connection is closed.
    at Promise (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:55:31)
    at new Promise (<anonymous>)
    at connectToNext (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:41:37)
    at resolve (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:100:29)
    at client.sentinel (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:139:24)
    at tryCatcher (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/utils.js:11:23)
    at promise.then (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/index.js:30:51)
    at process._tickCallback (internal/process/next_tick.js:178:7)
[ioredis] Unhandled error event: Error: All sentinels are unreachable. Retrying from scratch after 370ms. Last error: Connection is closed.
    at Promise (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:55:31)
    at new Promise (<anonymous>)
    at connectToNext (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:41:37)
    at resolve (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:100:29)
    at client.sentinel (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:139:24)
    at tryCatcher (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/utils.js:11:23)
    at promise.then (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/index.js:30:51)
    at process._tickCallback (internal/process/next_tick.js:178:7)
[ioredis] Unhandled error event: Error: All sentinels are unreachable. Retrying from scratch after 370ms. Last error: Connection is closed.
    at Promise (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:55:31)
    at new Promise (<anonymous>)
    at connectToNext (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:41:37)
    at resolve (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:100:29)
    at client.sentinel (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:156:24)
    at tryCatcher (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/utils.js:11:23)
    at promise.then (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/index.js:30:51)
    at process._tickCallback (internal/process/next_tick.js:178:7)
[ioredis] Unhandled error event: Error: All sentinels are unreachable. Retrying from scratch after 380ms. Last error: Connection is closed.
    at Promise (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:55:31)
    at new Promise (<anonymous>)
    at connectToNext (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:41:37)
    at resolve (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:100:29)
    at client.sentinel (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:139:24)
    at tryCatcher (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/utils.js:11:23)
    at promise.then (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/index.js:30:51)
    at process._tickCallback (internal/process/next_tick.js:178:7)
[ioredis] Unhandled error event: Error: All sentinels are unreachable. Retrying from scratch after 380ms. Last error: Connection is closed.
    at Promise (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:55:31)
    at new Promise (<anonymous>)
    at connectToNext (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:41:37)
    at resolve (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:100:29)
    at client.sentinel (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:156:24)
    at tryCatcher (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/utils.js:11:23)
    at promise.then (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/index.js:30:51)
    at process._tickCallback (internal/process/next_tick.js:178:7)
[ioredis] Unhandled error event: Error: All sentinels are unreachable. Retrying from scratch after 390ms. Last error: Connection is closed.
    at Promise (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:55:31)
    at new Promise (<anonymous>)
    at connectToNext (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:41:37)
    at resolve (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:100:29)
    at client.sentinel (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:156:24)
    at tryCatcher (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/utils.js:11:23)
    at promise.then (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/index.js:30:51)
    at process._tickCallback (internal/process/next_tick.js:178:7)
[ioredis] Unhandled error event: Error: All sentinels are unreachable. Retrying from scratch after 390ms. Last error: Connection is closed.
    at Promise (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:55:31)
    at new Promise (<anonymous>)
    at connectToNext (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:41:37)
    at resolve (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:100:29)
    at client.sentinel (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:139:24)
    at tryCatcher (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/utils.js:11:23)
    at promise.then (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/index.js:30:51)
    at process._tickCallback (internal/process/next_tick.js:178:7)
[ioredis] Unhandled error event: Error: All sentinels are unreachable. Retrying from scratch after 400ms. Last error: Connection is closed.
    at Promise (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:55:31)
    at new Promise (<anonymous>)
    at connectToNext (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:41:37)
    at resolve (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:100:29)
    at client.sentinel (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:156:24)
    at tryCatcher (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/utils.js:11:23)
    at promise.then (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/index.js:30:51)
    at process._tickCallback (internal/process/next_tick.js:178:7)
[ioredis] Unhandled error event: Error: All sentinels are unreachable. Retrying from scratch after 400ms. Last error: Connection is closed.
    at Promise (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:55:31)
    at new Promise (<anonymous>)
    at connectToNext (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:41:37)
    at resolve (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:100:29)
    at client.sentinel (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:139:24)
    at tryCatcher (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/utils.js:11:23)
    at promise.then (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/index.js:30:51)
    at process._tickCallback (internal/process/next_tick.js:178:7)
[ioredis] Unhandled error event: Error: All sentinels are unreachable. Retrying from scratch after 410ms. Last error: Connection is closed.
    at Promise (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:55:31)
    at new Promise (<anonymous>)
    at connectToNext (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:41:37)
    at resolve (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:100:29)
    at client.sentinel (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:156:24)
    at tryCatcher (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/utils.js:11:23)
    at promise.then (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/index.js:30:51)
    at process._tickCallback (internal/process/next_tick.js:178:7)
[ioredis] Unhandled error event: Error: All sentinels are unreachable. Retrying from scratch after 410ms. Last error: Connection is closed.
    at Promise (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:55:31)
    at new Promise (<anonymous>)
    at connectToNext (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:41:37)
    at resolve (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:100:29)
    at client.sentinel (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:139:24)
    at tryCatcher (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/utils.js:11:23)
    at promise.then (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/index.js:30:51)
    at process._tickCallback (internal/process/next_tick.js:178:7)
[ioredis] Unhandled error event: Error: All sentinels are unreachable. Retrying from scratch after 420ms. Last error: Connection is closed.
    at Promise (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:55:31)
    at new Promise (<anonymous>)
    at connectToNext (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:41:37)
    at resolve (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:100:29)
    at client.sentinel (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:139:24)
    at tryCatcher (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/utils.js:11:23)
    at promise.then (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/index.js:30:51)
    at process._tickCallback (internal/process/next_tick.js:178:7)
[ioredis] Unhandled error event: Error: All sentinels are unreachable. Retrying from scratch after 420ms. Last error: Connection is closed.
    at Promise (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:55:31)
    at new Promise (<anonymous>)
    at connectToNext (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:41:37)
    at resolve (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:100:29)
    at client.sentinel (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:156:24)
    at tryCatcher (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/utils.js:11:23)
    at promise.then (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/index.js:30:51)
    at process._tickCallback (internal/process/next_tick.js:178:7)
[ioredis] Unhandled error event: Error: All sentinels are unreachable. Retrying from scratch after 430ms. Last error: Connection is closed.
    at Promise (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:55:31)
    at new Promise (<anonymous>)
    at connectToNext (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:41:37)
    at resolve (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:100:29)
    at client.sentinel (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:156:24)
    at tryCatcher (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/utils.js:11:23)
    at promise.then (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/index.js:30:51)
    at process._tickCallback (internal/process/next_tick.js:178:7)
[ioredis] Unhandled error event: Error: All sentinels are unreachable. Retrying from scratch after 430ms. Last error: Connection is closed.
    at Promise (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:55:31)
    at new Promise (<anonymous>)
    at connectToNext (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:41:37)
    at resolve (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:100:29)
    at client.sentinel (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:139:24)
    at tryCatcher (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/utils.js:11:23)
    at promise.then (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/index.js:30:51)
    at process._tickCallback (internal/process/next_tick.js:178:7)
[ioredis] Unhandled error event: Error: All sentinels are unreachable. Retrying from scratch after 440ms. Last error: Connection is closed.
    at Promise (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:55:31)
    at new Promise (<anonymous>)
    at connectToNext (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:41:37)
    at resolve (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:100:29)
    at client.sentinel (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:139:24)
    at tryCatcher (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/utils.js:11:23)
    at promise.then (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/index.js:30:51)
    at process._tickCallback (internal/process/next_tick.js:178:7)
[ioredis] Unhandled error event: Error: All sentinels are unreachable. Retrying from scratch after 440ms. Last error: Connection is closed.
    at Promise (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:55:31)
    at new Promise (<anonymous>)
    at connectToNext (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:41:37)
    at resolve (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:100:29)
    at client.sentinel (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:156:24)
    at tryCatcher (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/utils.js:11:23)
    at promise.then (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/index.js:30:51)
    at process._tickCallback (internal/process/next_tick.js:178:7)
[ioredis] Unhandled error event: Error: All sentinels are unreachable. Retrying from scratch after 450ms. Last error: Connection is closed.
    at Promise (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:55:31)
    at new Promise (<anonymous>)
    at connectToNext (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:41:37)
    at resolve (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:100:29)
    at client.sentinel (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:156:24)
    at tryCatcher (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/utils.js:11:23)
    at promise.then (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/index.js:30:51)
    at process._tickCallback (internal/process/next_tick.js:178:7)
[ioredis] Unhandled error event: Error: All sentinels are unreachable. Retrying from scratch after 450ms. Last error: Connection is closed.
    at Promise (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:55:31)
    at new Promise (<anonymous>)
    at connectToNext (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:41:37)
    at resolve (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:100:29)
    at client.sentinel (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:139:24)
    at tryCatcher (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/utils.js:11:23)
    at promise.then (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/index.js:30:51)
    at process._tickCallback (internal/process/next_tick.js:178:7)
[ioredis] Unhandled error event: Error: All sentinels are unreachable. Retrying from scratch after 460ms. Last error: Connection is closed.
    at Promise (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:55:31)
    at new Promise (<anonymous>)
    at connectToNext (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:41:37)
    at resolve (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:100:29)
    at client.sentinel (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:139:24)
    at tryCatcher (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/utils.js:11:23)
    at promise.then (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/index.js:30:51)
    at process._tickCallback (internal/process/next_tick.js:178:7)
[ioredis] Unhandled error event: Error: All sentinels are unreachable. Retrying from scratch after 460ms. Last error: Connection is closed.
    at Promise (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:55:31)
    at new Promise (<anonymous>)
    at connectToNext (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:41:37)
    at resolve (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:100:29)
    at client.sentinel (/Users/linteng/www/127/tech/node-framework/node_modules/ioredis/built/connectors/SentinelConnector/index.js:156:24)
    at tryCatcher (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/utils.js:11:23)
    at promise.then (/Users/linteng/www/127/tech/node-framework/node_modules/standard-as-callback/built/index.js:30:51)
    at process._tickCallback (internal/process/next_tick.js:178:7)
/Users/linteng/www/127/tech/node-framework/libs/router/router.js:27
      console.log({this.request.pathname}, '---------------')
                       ^

SyntaxError: Unexpected token .
    at new Script (vm.js:74:7)
    at createScript (vm.js:246:10)
    at Object.runInThisContext (vm.js:298:10)
    at Module._compile (internal/modules/cjs/loader.js:646:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
/Users/linteng/www/127/tech/node-framework/libs/dbmanager/api.js:117
        default:
        ^^^^^^^

SyntaxError: More than one default clause in switch statement
    at new Script (vm.js:74:7)
    at createScript (vm.js:246:10)
    at Object.runInThisContext (vm.js:298:10)
    at Module._compile (internal/modules/cjs/loader.js:646:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
/Users/linteng/www/127/tech/node-framework/libs/session/redis.js:4
  reconnectOnError: function(err) {
  ^^^^^^^^^^^^^^^^

SyntaxError: Unexpected identifier
    at new Script (vm.js:74:7)
    at createScript (vm.js:246:10)
    at Object.runInThisContext (vm.js:298:10)
    at Module._compile (internal/modules/cjs/loader.js:646:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
/Users/linteng/www/127/tech/node-framework/libs/session/redis.js:7
  maxRetriesPerRequest: 1,
  ^^^^^^^^^^^^^^^^^^^^

SyntaxError: Unexpected identifier
    at new Script (vm.js:74:7)
    at createScript (vm.js:246:10)
    at Object.runInThisContext (vm.js:298:10)
    at Module._compile (internal/modules/cjs/loader.js:646:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
